@startuml
'https://plantuml.com/class-diagram

class History
class PaymentPlan
class Account
class Rating
class UserGUI
class Video
class Options
class Movie
class TVShowEpisode
class Season
class Title
class RealServer
class ProxyServer
class CPPMoviesMediator



Account *-- PaymentPlan
Account *-- History
Account o-- Rating
UserGUI o-- Account

CPPMoviesMediator o-- Account: Contains many
CPPMoviesMediator o-- Video
Video <-- Options
Video <|-- Movie
Video <|-- TVShowEpisode

TVShowEpisode <-- Season

(CPPMoviesMediator, Video) .. ProxyServer
ProxyServer .. RealServer




@enduml